const database = require ('../../services/database');

const baseQuery =

`SELECT
'ANALISECREDITO_RESPDS' TABELA , 'INSERT' OPERACAO,
TELEFONICA.ANALISECREDITO_RESPDS.IDS_ANALISECREDITO_RESPDS  IDS_ANALISECREDITO_RESPDS,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.CODRETORNO, ';| |"', '')  CODRETORNO,
TELEFONICA.ANALISECREDITO_RESPDS.MAXIMOPRODUTOS  MAXIMOPRODUTOS,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.MENSAGEM, ';| |"', '')  MENSAGEM,
TELEFONICA.ANALISECREDITO_RESPDS.SCORE  SCORE,
CASE WHEN TELEFONICA.ANALISECREDITO_RESPDS.SYS_CREATEDATE IS NULL THEN '' ELSE TO_CHAR(TELEFONICA.ANALISECREDITO_RESPDS.SYS_CREATEDATE, 'YYYY-MM-DD')||'t'||TO_CHAR(TELEFONICA.ANALISECREDITO_RESPDS.SYS_CREATEDATE, 'HH24:MI')||':'||SUBSTR(TO_CHAR(TELEFONICA.ANALISECREDITO_RESPDS.SYS_CREATEDATE, 'SSSSS'),1,2)||'.'||SUBSTR(TO_CHAR(TELEFONICA.ANALISECREDITO_RESPDS.SYS_CREATEDATE, 'SSSSS'),3,3)||'z'  END   SYS_CREATEDATE,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.REPRESENTANTELEGAL, ';| |"', '')  REPRESENTANTELEGAL,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.ALCADA, ';| |"', '')  ALCADA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.COMENTARIO_ALCADA, ';| |"', '')  COMENTARIO_ALCADA,
TELEFONICA.ANALISECREDITO_RESPDS.COUNTCOMERCIAL  COUNTCOMERCIAL,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.DATA_VALIDADE_CONSULTA, ';| |"', '')  DATA_VALIDADE_CONSULTA,
TELEFONICA.ANALISECREDITO_RESPDS.DEBT_VALUE  DEBT_VALUE,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.ETAPA, ';| |"', '')  ETAPA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.FLAG_DIVIDA_INTERNA, ';| |"', '')  FLAG_DIVIDA_INTERNA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.FLAG_RESTRICAO_EXTERNA, ';| |"', '')  FLAG_RESTRICAO_EXTERNA,
TELEFONICA.ANALISECREDITO_RESPDS.LIMITE_COT  LIMITE_COT,
TELEFONICA.ANALISECREDITO_RESPDS.LIMITE_OPO  LIMITE_OPO,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.MOTIVO, ';| |"', '')  MOTIVO,
TELEFONICA.ANALISECREDITO_RESPDS.POTENCIAL_LIMIT  POTENCIAL_LIMIT,
TELEFONICA.ANALISECREDITO_RESPDS.PRIORIDADE  PRIORIDADE,
TELEFONICA.ANALISECREDITO_RESPDS.REMAINING_LIMIT  REMAINING_LIMIT,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.RESPONSECODENC, ';| |"', '')  RESPONSECODENC,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.RESPONSEMESSAGENC, ';| |"', '')  RESPONSEMESSAGENC,
TELEFONICA.ANALISECREDITO_RESPDS.RISCOTOTAL  RISCOTOTAL,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SLAEMDIAS, ';| |"', '')  SLAEMDIAS,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.STATUS, ';| |"', '')  STATUS,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.TK_MED_VENDAS, ';| |"', '')  TK_MED_VENDAS,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.TX_APROV_AUT, ';| |"', '')  TX_APROV_AUT,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.TX_APROV_FINAL, ';| |"', '')  TX_APROV_FINAL,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.TX_APROV_MAN, ';| |"', '')  TX_APROV_MAN,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.TX_APROV_MED_AUT, ';| |"', '')  TX_APROV_MED_AUT,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.TX_APROV_MED_FINAL, ';| |"', '')  TX_APROV_MED_FINAL,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.TX_APROV_MED_MAN, ';| |"', '')  TX_APROV_MED_MAN,
TELEFONICA.ANALISECREDITO_RESPDS.VALORCONSUMIDO  VALORCONSUMIDO,
TELEFONICA.ANALISECREDITO_RESPDS.COUNTREPROVADOSANALISEMANUAL  COUNTREPROVADOSANALISEMANUAL,
TELEFONICA.ANALISECREDITO_RESPDS.COUNTPENDCOMERCIALANALISEMANUA  COUNTPENDCOMERCIALANALISEMANUA,
TELEFONICA.ANALISECREDITO_RESPDS.COUNTMESA  COUNTMESA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.PARECER_EXTERNO, ';| |"', '')  PARECER_EXTERNO,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.PARECER_INTERNO, ';| |"', '')  PARECER_INTERNO,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.BEHAVIORSCORE, ';| |"', '')  BEHAVIORSCORE,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.CEPRELATO, ';| |"', '')  CEPRELATO,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.CLASSESOCIAL, ';| |"', '')  CLASSESOCIAL,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.CLASSIFICACAOARMARIO, ';| |"', '')  CLASSIFICACAOARMARIO,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.CODIGOCARTA, ';| |"', '')  CODIGOCARTA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.CODIGOPOSTALRETORNOSERASA, ';| |"', '')  CODIGOPOSTALRETORNOSERASA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.DATADIVIDAMAISANTIGA, ';| |"', '')  DATADIVIDAMAISANTIGA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.DATAFUNDACAORELATO, ';| |"', '')  DATAFUNDACAORELATO,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.DATANASCIMENTORETORNOSERASA, ';| |"', '')  DATANASCIMENTORETORNOSERASA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.DECISAOCODIGODOCUMENTOSREQUERI, ';| |"', '')  DECISAOCODIGODOCUMENTOSREQUERI,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.DECISAOFINAL, ';| |"', '')  DECISAOFINAL,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.DECISAOINTERNETANALISTA, ';| |"', '') DECISAOINTERNETANALISTA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.DECISAOLINHATELEFONICAANALISTA, ';| |"', '')  DECISAOLINHATELEFONICAANALISTA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.DECISAOLONGADISTANCIAANALISTA, ';| |"', '')  DECISAOLONGADISTANCIAANALISTA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.DECISAOOUTROSANALISTAS, ';| |"', '')  DECISAOOUTROSANALISTAS,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.DECISAOVASANALISTA, ';| |"', '')  DECISAOVASANALISTA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.FATURAMENTOANTECIPADOTARIFAINS, ';| |"', '')  FATURAMENTOANTECIPADOTARIFAINS,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.GRAURISCO, ';| |"', '')  GRAURISCO,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.ISENTO, ';| |"', '')  ISENTO,
TELEFONICA.ANALISECREDITO_RESPDS.LIMITECREDITO  LIMITECREDITO,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.METODOPAGAMENTO, ';| |"', '')  METODOPAGAMENTO,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.MOTIVODECISAOFINAL, ';| |"', '')  MOTIVODECISAOFINAL,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.NOMEARMARIOOSP, ';| |"', '')  NOMEARMARIOOSP,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.NOMEEMPRESARELATO, ';| |"', '')  NOMEEMPRESARELATO,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.NOMEMAERETORNOSERASA, ';| |"', '')  NOMEMAERETORNOSERASA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.NOMERETORNOSERASA, ';| |"', '')  NOMERETORNOSERASA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.RISKSCORE, ';| |"', '')  RISKSCORE,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SERASANOMEMAE, ';| |"', '')  SERASANOMEMAE,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SERASANOMETITULARCPF, ';| |"', '')  SERASANOMETITULARCPF,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDNUM1, ';| |"', '')  SPAREFIELDNUM1,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDNUM2, ';| |"', '')  SPAREFIELDNUM2,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDNUM21, ';| |"', '')  SPAREFIELDNUM21,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDNUM22, ';| |"', '')  SPAREFIELDNUM22,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDNUM23, ';| |"', '')  SPAREFIELDNUM23,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDNUM24, ';| |"', '')  SPAREFIELDNUM24,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDNUM25, ';| |"', '')  SPAREFIELDNUM25,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDNUM26, ';| |"', '')  SPAREFIELDNUM26,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDNUM27, ';| |"', '')  SPAREFIELDNUM27,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDNUM28, ';| |"', '')  SPAREFIELDNUM28,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDNUM29, ';| |"', '')  SPAREFIELDNUM29,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDNUM30, ';| |"', '')  SPAREFIELDNUM30,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDNUM5, ';| |"', '')  SPAREFIELDNUM5,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDNUM8, ';| |"', '')  SPAREFIELDNUM8,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDTEXT26, ';| |"', '')  SPAREFIELDTEXT26,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDTEXT27, ';| |"', '')  SPAREFIELDTEXT27,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDTEXT28, ';| |"', '')  SPAREFIELDTEXT28,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDTEXT29, ';| |"', '')  SPAREFIELDTEXT29,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDTEXT30, ';| |"', '')  SPAREFIELDTEXT30,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDTEXT31, ';| |"', '')  SPAREFIELDTEXT31,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDTEXT32, ';| |"', '')  SPAREFIELDTEXT32,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDTEXT33, ';| |"', '')  SPAREFIELDTEXT33,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDTEXT34, ';| |"', '')  SPAREFIELDTEXT34,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDTEXT35, ';| |"', '')  SPAREFIELDTEXT35,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.SPAREFIELDTEXT6, ';| |"', '')  SPAREFIELDTEXT6,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.STATUSPROPOSTA, ';| |"', '')  STATUSPROPOSTA,
REGEXP_REPLACE(TELEFONICA.ANALISECREDITO_RESPDS.TIPOPRODUTOIDRESULTADOSCRIPT, ';| |"', '')  TIPOPRODUTOIDRESULTADOSCRIPT,
TELEFONICA.ANALISECREDITO_RESPDS.VALORINTERNODEVIDO VALORINTERNODEVIDO
from TELEFONICA.ANALISECREDITO_RESPDS INNER JOIN TELEFONICA.DADOSPROPOSTADS
ON TELEFONICA.ANALISECREDITO_RESPDS.IDS_ANALISECREDITO_RESPDS = TELEFONICA.DADOSPROPOSTADS.IDS_ANALISECREDITO_RESPDS and DADOSPROPOSTADS.IDS_DADOSPROPOSTADS = IDS_DADOSPROPOSTADS`; 

/*
`SELECT 'ANALISECREDITO_RESPDS' TABELA, 'INSERT' OPERACAO, SYSDATE DATA_STREAM, ANALISECREDITO_RESPDS.* 
from ANALISECREDITO_RESPDS , DADOSPROPOSTADS 
WHERE  ANALISECREDITO_RESPDS.IDS_ANALISECREDITO_RESPDS = DADOSPROPOSTADS.IDS_ANALISECREDITO_RESPDS and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.IDS_DADOSPROPOSTADS = context.id;

    query += `\nwhere IDS_DADOSPROPOSTADS = :IDS_DADOSPROPOSTADS`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
