const database = require ('../../services/database');

const baseQuery =

`SELECT 'ATLYS_REQ_LDS' TABELA, 'INSERT' OPERACAO, 
TELEFONICA.ATLYS_REQ_LDS.IDS_ATLYS_REQ_LDS ,
TELEFONICA.ATLYS_REQ_LDS.CEP ,
TELEFONICA.ATLYS_REQ_LDS.DOCUMENTO ,
TELEFONICA.ATLYS_REQ_LDS.DTNASC ,
TELEFONICA.ATLYS_REQ_LDS.SYS_CREATEDATE ,
TELEFONICA.ATLYS_REQ_LDS.USUARIO ,
TELEFONICA.ATLYS_REQ_LDS.DDD ,
TELEFONICA.ATLYS_REQ_LDS.UF from ATLYS_REQ_LDS INNER JOIN DADOSPROPOSTADS ON  ATLYS_REQ_LDS.IDS_ATLYS_REQ_LDS = DADOSPROPOSTADS.IDS_ATLYS_REQ_LDS  and DADOSPROPOSTADS.IDS_DADOSPROPOSTADS = IDS_DADOSPROPOSTADS`;


/*
`SELECT 'ATLYS_REQ_LDS' TABELA, 'INSERT' OPERACAO, SYSDATE DATA_STREAM, ATLYS_REQ_LDS.* 
from ATLYS_REQ_LDS , DADOSPROPOSTADS 
WHERE  ATLYS_REQ_LDS.IDS_ATLYS_REQ_LDS = DADOSPROPOSTADS.IDS_ATLYS_REQ_LDS and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.IDS_DADOSPROPOSTADS = context.id;

    query += `\nwhere IDS_DADOSPROPOSTADS = :IDS_DADOSPROPOSTADS`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
