const database = require ('../../services/database');

const baseQuery =

`SELECT 'BLACKLIST_PF_FIXO' TABELA, 'INSERT' OPERACAO, 
TELEFONICA.BLACKLIST_PF_FIXO.IDS_BLACKLIST_PF_FIXO ,
TELEFONICA.BLACKLIST_PF_FIXO.COD_ARQ_PROCESSAR ,
TELEFONICA.BLACKLIST_PF_FIXO.CODIGOERRO ,
TELEFONICA.BLACKLIST_PF_FIXO.CPF ,
TELEFONICA.BLACKLIST_PF_FIXO.DATA_BLK ,
TELEFONICA.BLACKLIST_PF_FIXO.DESCRICAOERRO ,
TELEFONICA.BLACKLIST_PF_FIXO.HORA ,
TELEFONICA.BLACKLIST_PF_FIXO.MOTIVO ,
TELEFONICA.BLACKLIST_PF_FIXO.SYS_CREATEDATE ,
TELEFONICA.BLACKLIST_PF_FIXO.UF ,
TELEFONICA.BLACKLIST_PF_FIXO.AGING ,
TELEFONICA.BLACKLIST_PF_FIXO.OFERTA ,
TELEFONICA.BLACKLIST_PF_FIXO.SALDO from BLACKLIST_PF_FIXO INNER JOIN DADOSPROPOSTADS ON  BLACKLIST_PF_FIXO.IDS_BLACKLIST_PF_FIXO = DADOSPROPOSTADS.IDS_BLACKLIST_PF_FIXO  and DADOSPROPOSTADS.IDS_DADOSPROPOSTADS = IDS_DADOSPROPOSTADS `;


/*
`SELECT 'BLACKLIST_PF_FIXO' TABELA, 'INSERT' OPERACAO, SYSDATE DATA_STREAM, BLACKLIST_PF_FIXO.* 
from BLACKLIST_PF_FIXO , DADOSPROPOSTADS 
WHERE  BLACKLIST_PF_FIXO.IDS_BLACKLIST_PF_FIXO = DADOSPROPOSTADS.IDS_BLACKLIST_PF_FIXO and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/


async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.IDS_DADOSPROPOSTADS = context.id;

    query += `\nwhere IDS_DADOSPROPOSTADS = :IDS_DADOSPROPOSTADS`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find
