const database = require ('../../services/database');

const baseQuery =

`SELECT 'BLACKLIST_PJ_FIXO' TABELA, 'INSERT' OPERACAO, 
TELEFONICA.BLACKLIST_PJ_FIXO.IDS_BLACKLIST_PJ_FIXO ,
TELEFONICA.BLACKLIST_PJ_FIXO.CNPJ ,
TELEFONICA.BLACKLIST_PJ_FIXO.COD_ARQ_PROCESSAR ,
TELEFONICA.BLACKLIST_PJ_FIXO.CODIGOERRO ,
TELEFONICA.BLACKLIST_PJ_FIXO.DATA_BLK ,
TELEFONICA.BLACKLIST_PJ_FIXO.DESCRICAOERRO ,
TELEFONICA.BLACKLIST_PJ_FIXO.HORA ,
TELEFONICA.BLACKLIST_PJ_FIXO.MOTIVO ,
TELEFONICA.BLACKLIST_PJ_FIXO.SYS_CREATEDATE ,
TELEFONICA.BLACKLIST_PJ_FIXO.UF ,
TELEFONICA.BLACKLIST_PJ_FIXO.AGING ,
TELEFONICA.BLACKLIST_PJ_FIXO.OFERTA ,
TELEFONICA.BLACKLIST_PJ_FIXO.SALDO from BLACKLIST_PJ_FIXO INNER JOIN DADOSPROPOSTADS ON  BLACKLIST_PJ_FIXO.IDS_BLACKLIST_PJ_FIXO = DADOSPROPOSTADS.IDS_BLACKLIST_PJ_FIXO  and DADOSPROPOSTADS.IDS_DADOSPROPOSTADS = IDS_DADOSPROPOSTADS`;

/*
`SELECT 'BLACKLIST_PJ_FIXO' TABELA, 'INSERT' OPERACAO, SYSDATE DATA_STREAM, BLACKLIST_PJ_FIXO.* 
from BLACKLIST_PJ_FIXO , DADOSPROPOSTADS 
WHERE  BLACKLIST_PJ_FIXO.IDS_BLACKLIST_PJ_FIXO = DADOSPROPOSTADS.IDS_BLACKLIST_PJ_FIXO and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
*/


async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.IDS_DADOSPROPOSTADS = context.id;

    query += `\nwhere IDS_DADOSPROPOSTADS = :IDS_DADOSPROPOSTADS`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
