const database = require ('../../services/database');

const baseQuery = 

`SELECT 'BLACKLIST_PJ_MOVEL' TABELA, 'INSERT' OPERACAO, 
TELEFONICA.BLACKLIST_PJ_MOVEL.IDS_BLACKLIST_PJ_MOVEL ,
TELEFONICA.BLACKLIST_PJ_MOVEL.CNPJ ,
TELEFONICA.BLACKLIST_PJ_MOVEL.COD_ARQ_PROCESSAR ,
TELEFONICA.BLACKLIST_PJ_MOVEL.CODIGOERRO ,
TELEFONICA.BLACKLIST_PJ_MOVEL.DATA_BLK ,
TELEFONICA.BLACKLIST_PJ_MOVEL.DESCRICAOERRO ,
TELEFONICA.BLACKLIST_PJ_MOVEL.HORA ,
TELEFONICA.BLACKLIST_PJ_MOVEL.MOTIVO ,
TELEFONICA.BLACKLIST_PJ_MOVEL.PLANO ,
TELEFONICA.BLACKLIST_PJ_MOVEL.SYS_CREATEDATE ,
TELEFONICA.BLACKLIST_PJ_MOVEL.UF ,
TELEFONICA.BLACKLIST_PJ_MOVEL.AGING ,
TELEFONICA.BLACKLIST_PJ_MOVEL.SALDO ,
TELEFONICA.BLACKLIST_PJ_MOVEL.OFERTA from BLACKLIST_PJ_MOVEL INNER JOIN DADOSPROPOSTADS ON  BLACKLIST_PJ_MOVEL.IDS_BLACKLIST_PJ_MOVEL = DADOSPROPOSTADS.IDS_BLACKLIST_PJ_MOVEL  and DADOSPROPOSTADS.IDS_DADOSPROPOSTADS = IDS_DADOSPROPOSTADS `;

/*
`SELECT 'BLACKLIST_PJ_MOVEL' TABELA, 'INSERT' OPERACAO, SYSDATE DATA_STREAM, BLACKLIST_PJ_MOVEL.* 
from BLACKLIST_PJ_MOVEL , DADOSPROPOSTADS 
WHERE  BLACKLIST_PJ_MOVEL.IDS_BLACKLIST_PJ_MOVEL = DADOSPROPOSTADS.IDS_BLACKLIST_PJ_MOVEL and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/
async function find(context) {
  let query = baseQuery;
  const binds = {};
 
  if (context.id) {
    binds.IDS_DADOSPROPOSTADS = context.id;
 
    query += `\nwhere IDS_DADOSPROPOSTADS = :IDS_DADOSPROPOSTADS`;
  }
 
  const result = await database.simpleExecute(query, binds);
 
  return result.rows;
}
 
module.exports.find = find;

