const database = require ('../../services/database');

const baseQuery =

`SELECT 'BW_LIST_DET_PROCESSAMENTO' TABELA, 'INSERT' OPERACAO, 
BW_LIST_DET_PROCESSAMENTO.IDS_BW_LIST_DET_PROCESSAMENTO ,
BW_LIST_DET_PROCESSAMENTO.ARRIDX_DADOSPROPOSTADS ,
BW_LIST_DET_PROCESSAMENTO.CD_ARQ_PROCESSADO ,
BW_LIST_DET_PROCESSAMENTO.DT_FIM_PROCESSAMENTO ,
BW_LIST_DET_PROCESSAMENTO.DT_INI_PROCESSAMENTO ,
BW_LIST_DET_PROCESSAMENTO.IND_ARQ_VALIDO ,
BW_LIST_DET_PROCESSAMENTO.NOME_ARQ_PROCESSADO ,
BW_LIST_DET_PROCESSAMENTO.QTD_REG_INVALIDOS ,
BW_LIST_DET_PROCESSAMENTO.QTD_REG_VALIDOS ,
BW_LIST_DET_PROCESSAMENTO.SYS_CREATEDATE ,
BW_LIST_DET_PROCESSAMENTO.IDS_DADOSPROPOSTADS from BW_LIST_DET_PROCESSAMENTO `;


/*
`SELECT 'BW_LIST_DET_PROCESSAMENTO' TABELA, 'INSERT' OPERACAO, SYSDATE DATA_STREAM, BW_LIST_DET_PROCESSAMENTO.* 
from BW_LIST_DET_PROCESSAMENTO , DADOSPROPOSTADS 
WHERE  BW_LIST_DET_PROCESSAMENTO.IDS_DADOSPROPOSTADS = DADOSPROPOSTADS.IDS_DADOSPROPOSTADS and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.IDS_DADOSPROPOSTADS = context.id;

    query += `\nwhere IDS_DADOSPROPOSTADS = :IDS_DADOSPROPOSTADS`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
