const database = require ('../../services/database');

const baseQuery =

`SELECT 'CONSULTACANAL_RESP_LDS' TABELA, 'INSERT' OPERACAO, 
CONSULTACANAL_RESP_LDS.IDS_CONSULTACANAL_RESP_LDS ,
CONSULTACANAL_RESP_LDS.CODIGO ,
CONSULTACANAL_RESP_LDS.CODIGOPLANO ,
CONSULTACANAL_RESP_LDS.COR ,
CONSULTACANAL_RESP_LDS.DATAHORA ,
CONSULTACANAL_RESP_LDS.NOMECLIENTE ,
CONSULTACANAL_RESP_LDS.NOMEMAE ,
CONSULTACANAL_RESP_LDS.QTDE_PROTESTOS_ATE_DATA ,
CONSULTACANAL_RESP_LDS.RECOMENDACAO ,
CONSULTACANAL_RESP_LDS.RESTRITIVO ,
CONSULTACANAL_RESP_LDS.SCORE ,
CONSULTACANAL_RESP_LDS.STATUS ,
CONSULTACANAL_RESP_LDS.SYS_CREATEDATE from CONSULTACANAL_RESP_LDS INNER JOIN DADOSPROPOSTADS ON  CONSULTACANAL_RESP_LDS.IDS_CONSULTACANAL_RESP_LDS = DADOSPROPOSTADS.IDS_CONSULTACANAL_RESP_LDS  and DADOSPROPOSTADS.IDS_DADOSPROPOSTADS = IDS_DADOSPROPOSTADS `;

/*
`SELECT 'CONSULTACANAL_RESP_LDS' TABELA, 'INSERT' OPERACAO, SYSDATE DATA_STREAM, CONSULTACANAL_RESP_LDS.* 
from CONSULTACANAL_RESP_LDS , DADOSPROPOSTADS 
WHERE  CONSULTACANAL_RESP_LDS.IDS_CONSULTACANAL_RESP_LDS = DADOSPROPOSTADS.IDS_CONSULTACANAL_RESP_LDS and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.IDS_DADOSPROPOSTADS = context.id;

    query += `\nwhere IDS_DADOSPROPOSTADS = :IDS_DADOSPROPOSTADS`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
