const database = require ('../../services/database');

const baseQuery =

`SELECT 'CONSULTASIEBELREQ' TABELA, 'INSERT' OPERACAO, 
CONSULTASIEBELREQ.IDS_CONSULTASIEBELREQ ,
CONSULTASIEBELREQ.DO_APD ,
CONSULTASIEBELREQ.DO_BEHAVIOR ,
CONSULTASIEBELREQ.DO_BLACKLIST_CREDITO ,
CONSULTASIEBELREQ.DO_CANAL_ATENDIMENTO ,
CONSULTASIEBELREQ.DO_CARTEIRA ,
CONSULTASIEBELREQ.DO_CEP ,
CONSULTASIEBELREQ.DO_CEP_SUSPEITO ,
CONSULTASIEBELREQ.DO_CEP_INF ,
CONSULTASIEBELREQ.DO_CLASSIFICACAO_DE_RISCO ,
CONSULTASIEBELREQ.DO_CODIGO_ESPECIAL ,
CONSULTASIEBELREQ.DO_CODIGO_ESPECIAL_VAL ,
CONSULTASIEBELREQ.DO_DADOS_AVANCADOS ,
CONSULTASIEBELREQ.DO_DADOS_AVANCADOS_VAL ,
CONSULTASIEBELREQ.DO_DATACENTER ,
CONSULTASIEBELREQ.DO_DATACENTER_VAL ,
CONSULTASIEBELREQ.DO_DTNASC ,
CONSULTASIEBELREQ.DO_EILD ,
CONSULTASIEBELREQ.DO_EILD_REGULADO ,
CONSULTASIEBELREQ.DO_EILD_REGULADO_VAL ,
CONSULTASIEBELREQ.DO_EILD_VAL ,
CONSULTASIEBELREQ.DO_FAIXA_CEP ,
CONSULTASIEBELREQ.DO_FAIXA_NCDD_TLCO ,
CONSULTASIEBELREQ.DO_FAIXA_NCDD_TLCO_PURO ,
CONSULTASIEBELREQ.DO_FAIXA_PENETRACAO ,
CONSULTASIEBELREQ.DO_FAIXA_RESTRITIVOS ,
CONSULTASIEBELREQ.DO_FWT ,
CONSULTASIEBELREQ.DO_FWT_VAL ,
CONSULTASIEBELREQ.DO_GRAFIA_MAE ,
CONSULTASIEBELREQ.DO_HISTORICO_DE_COTACOES ,
CONSULTASIEBELREQ.DO_INADIMPLENCIA_INTERNA ,
CONSULTASIEBELREQ.DO_INADOM ,
CONSULTASIEBELREQ.DO_LD15 ,
CONSULTASIEBELREQ.DO_LD15_FIXA ,
CONSULTASIEBELREQ.DO_LD15_FIXA_VAL ,
CONSULTASIEBELREQ.DO_LD15_VAL ,
CONSULTASIEBELREQ.DO_LIMITE_DE_CREDITO ,
CONSULTASIEBELREQ.DO_LIMITES_SCORE ,
CONSULTASIEBELREQ.DO_M2M ,
CONSULTASIEBELREQ.DO_M2M_VAL ,
CONSULTASIEBELREQ.DO_MOVEL_DADOS ,
CONSULTASIEBELREQ.DO_MOVEL_DADOS_VAL ,
CONSULTASIEBELREQ.DO_MOVEL_VOZ_CONTROLE ,
CONSULTASIEBELREQ.DO_MOVEL_VOZ_CONTROLE_VAL ,
CONSULTASIEBELREQ.DO_MOVEL_VOZ_POS ,
CONSULTASIEBELREQ.DO_MOVEL_VOZ_POS_VAL ,
CONSULTASIEBELREQ.DO_MULTAS ,
CONSULTASIEBELREQ.DO_NOME ,
CONSULTASIEBELREQ.DO_NOME_DA_MAE ,
CONSULTASIEBELREQ.DO_PARECER_INTERNO ,
CONSULTASIEBELREQ.DO_REDE_INTELIGENTE ,
CONSULTASIEBELREQ.DO_REDE_INTELIGENTE_VAL ,
CONSULTASIEBELREQ.DO_REDE_INTELIGENTEL ,
CONSULTASIEBELREQ.DO_REGIONAL_ATENDIMENTO ,
CONSULTASIEBELREQ.DO_SOLUCIONA_TI ,
CONSULTASIEBELREQ.DO_SOLUCIONA_TI_VAL ,
CONSULTASIEBELREQ.DO_TERMINAL ,
CONSULTASIEBELREQ.DO_TERMINAL_VAL ,
CONSULTASIEBELREQ.DO_TI ,
CONSULTASIEBELREQ.DO_TI_VAL ,
CONSULTASIEBELREQ.DO_TIPO_DE_ANALISE ,
CONSULTASIEBELREQ.DO_TIPO_DE_CARTEIRA ,
CONSULTASIEBELREQ.DO_TIPO_DE_FLUXO ,
CONSULTASIEBELREQ.DO_TIPO_DE_VENDA ,
CONSULTASIEBELREQ.DO_TRANSPORTE ,
CONSULTASIEBELREQ.DO_TRANSPORTE_VAL ,
CONSULTASIEBELREQ.DO_TV_DTH ,
CONSULTASIEBELREQ.DO_TV_DTH_VAL ,
CONSULTASIEBELREQ.DO_UF ,
CONSULTASIEBELREQ.DO_VIVO_INTERNET_FIXA ,
CONSULTASIEBELREQ.DO_VIVO_INTERNET_FIXA_VAL ,
CONSULTASIEBELREQ.DO_VOZ_AVANCADA_JUNTOR ,
CONSULTASIEBELREQ.DO_VOZ_AVANCADA_JUNTOR_VAL ,
CONSULTASIEBELREQ.DO_VOZ_AVANCADA_RAMAL ,
CONSULTASIEBELREQ.DO_VOZ_AVANCADA_RAMAL_VAL ,
CONSULTASIEBELREQ.DO_WHITE_LIST ,
CONSULTASIEBELREQ.DOCUMENTO ,
CONSULTASIEBELREQ.LOGIN ,
CONSULTASIEBELREQ.SENHA ,
CONSULTASIEBELREQ.SYS_CREATEDATE ,
CONSULTASIEBELREQ.T01_DATA_NASCIMENTO ,
CONSULTASIEBELREQ.T01_TIPO_ANALISE ,
CONSULTASIEBELREQ.T02_CEP ,
CONSULTASIEBELREQ.T02_POLITICA_CONCESSAO ,
CONSULTASIEBELREQ.T03_DATA_FUNDACAO ,
CONSULTASIEBELREQ.T03_NOME_CLIENTE ,
CONSULTASIEBELREQ.T04_CEP ,
CONSULTASIEBELREQ.T05_RAZAO_SOCIAL ,
CONSULTASIEBELREQ.T07_NRO_EMPREGOS_GERADOS ,
CONSULTASIEBELREQ.T08_FATURAMENTO_TOTAL ,
CONSULTASIEBELREQ.T09_CUSTO_ALUGUEL ,
CONSULTASIEBELREQ.T10_FOLHA_PAGAMENTO ,
CONSULTASIEBELREQ.T11_VALOR_CREDITO_SOLICITADO ,
CONSULTASIEBELREQ.T12_PRAZO_PARA_PAGAMENTO ,
CONSULTASIEBELREQ.T13_QUANTIDADE_APARELHOS ,
CONSULTASIEBELREQ.T15_SISTEMA_CDA ,
CONSULTASIEBELREQ.T16_DATA_PARCELA_VENC_NAO_PAGA ,
CONSULTASIEBELREQ.T17_VALOR_TOTAL_DIVIDA_ABERTO ,
CONSULTASIEBELREQ.T18_QTDE_ALTA_VOZ ,
CONSULTASIEBELREQ.T19_VALOR_ALTA_VOZ ,
CONSULTASIEBELREQ.T20_QTDE_ALTA_DADOS ,
CONSULTASIEBELREQ.T21_VALOR_ALTA_DADOS ,
CONSULTASIEBELREQ.T22_QTDE_TROCA_VENDA ,
CONSULTASIEBELREQ.T23_VALOR_TROCAS_VENDA ,
CONSULTASIEBELREQ.VIVOQTDEDEALTASDADOSFIXO ,
CONSULTASIEBELREQ.VIVOQTDEDEALTASVOZFIXO ,
CONSULTASIEBELREQ.VIVOQTDETROCAVENDAFIXO from CONSULTASIEBELREQ INNER JOIN DADOSPROPOSTADS ON  CONSULTASIEBELREQ.IDS_CONSULTASIEBELREQ = DADOSPROPOSTADS.IDS_CONSULTASIEBELREQ  and DADOSPROPOSTADS.IDS_DADOSPROPOSTADS = IDS_DADOSPROPOSTADS `;

/*
`SELECT 'CONSULTASIEBELRESP' TABELA, 'INSERT' OPERACAO, SYSDATE DATA_STREAM, CONSULTASIEBELRESP.* 
from CONSULTASIEBELRESP , DADOSPROPOSTADS 
WHERE  CONSULTASIEBELRESP.IDS_CONSULTASIEBELRESP = DADOSPROPOSTADS.IDS_CONSULTASIEBELRESP and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.IDS_DADOSPROPOSTADS = context.id;

    query += `\nwhere IDS_DADOSPROPOSTADS = :IDS_DADOSPROPOSTADS`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
