const database = require ('../../services/database');

const baseQuery =

`SELECT 'CONTROLE' TABELA, 'INSERT' OPERACAO, 
CONTROLE.IDS_CONTROLE ,
CONTROLE.ANALISEMANUAL ,
CONTROLE.BUREAUCHAMADO_1_ ,
CONTROLE.BUREAUCHAMADO_2_ ,
CONTROLE.BUREAUCHAMADO_3_ ,
CONTROLE.BUREAUCHAMADO_4_ ,
CONTROLE.BUREAUCHAMADO_5_ ,
CONTROLE.CODRETORNOBVSPF ,
CONTROLE.CODRETORNOINTERNALCHECK ,
CONTROLE.CODRETORNOSERA11 ,
CONTROLE.DATAALCADA ,
CONTROLE.DATAANALISEMANUAL ,
CONTROLE.DATACHAMADABVSPF ,
CONTROLE.DATACHAMADAINTERNALCHECK ,
CONTROLE.DATACHAMADASERA11 ,
CONTROLE.DATACRIAEXCECAO ,
CONTROLE.NUMPROPOSTAATUAL ,
CONTROLE.NUMPROPOSTALOOKUP ,
CONTROLE.QTDEPROPLOOKUP ,
CONTROLE.SYS_CREATEDATE ,
CONTROLE.USUARIOALCADA ,
CONTROLE.USUARIOANALISEMANUAL ,
CONTROLE.USUARIOCRIAEXCECAO ,
CONTROLE.ANALISEINTERNA_HORAFIM ,
CONTROLE.ANALISEINTERNA_HORAINICIO ,
CONTROLE.ANALISEINTERNA_TEMPOTOTAL ,
CONTROLE.BASECEP_HORAFIM ,
CONTROLE.BASECEP_HORAINICIO ,
CONTROLE.BASECEP_TEMPOTOTAL ,
CONTROLE.BLKEWL_HORAFIM ,
CONTROLE.BLKEWL_HORAINICIO ,
CONTROLE.BLKEWL_TEMPOTOTAL ,
CONTROLE.BUREAU_HORAFIM ,
CONTROLE.BUREAU_HORAINICIO ,
CONTROLE.BUREAU_TEMPOTOTAL ,
CONTROLE.CONSOLIDADO_HORAFIM ,
CONTROLE.CONSOLIDADO_HORAINICIO ,
CONTROLE.CONSOLIDADO_TEMPOTOTAL ,
CONTROLE.DECISAOFINAL_HORAFIM ,
CONTROLE.DECISAOFINAL_HORAINICIO ,
CONTROLE.DECISAOFINAL_TEMPOTOTAL ,
CONTROLE.FRAUDEEINADIMP_HORAFIM ,
CONTROLE.FRAUDEEINADIMP_HORAINICIO ,
CONTROLE.FRAUDEEINADIMP_TEMPOTOTAL ,
CONTROLE.INTERNALCHECK_HORAFIM ,
CONTROLE.INTERNALCHECK_HORAINICIO ,
CONTROLE.INTERNALCHECK_TEMPOTOTAL ,
CONTROLE.PARAMETROSDA_HORAFIM ,
CONTROLE.PARAMETROSDA_HORAINICIO ,
CONTROLE.PARAMETROSDA_TEMPOTOTAL ,
CONTROLE.PROPOSTA_HORAFIM ,
CONTROLE.PROPOSTA_HORAINICIO ,
CONTROLE.PROPOSTA_TEMPOTOTAL ,
CONTROLE.BVSPF_CHAMAR ,
CONTROLE.BVSPF_CHAMOU ,
CONTROLE.BVSPF_CODIGORETORNO ,
CONTROLE.BVSPF_DATAHORACONSULTA ,
CONTROLE.BVSPF_DATAHORAFIM ,
CONTROLE.BVSPF_DATAHORAINICIO ,
CONTROLE.BVSPF_DATARESPOSTA ,
CONTROLE.BVSPF_MENSAGEM ,
CONTROLE.BVSPF_TEMPOTOTAL ,
CONTROLE.BVSPJ_CHAMAR ,
CONTROLE.BVSPJ_CHAMOU ,
CONTROLE.BVSPJ_CODIGORETORNO ,
CONTROLE.BVSPJ_DATAHORACONSULTA ,
CONTROLE.BVSPJ_DATAHORAFIM ,
CONTROLE.BVSPJ_DATAHORAINICIO ,
CONTROLE.BVSPJ_DATARESPOSTA ,
CONTROLE.BVSPJ_MENSAGEM ,
CONTROLE.BVSPJ_TEMPOTOTAL ,
CONTROLE.CREDITINFORMATION_CHAMAR ,
CONTROLE.CREDITINFORMATION_CHAMOU ,
CONTROLE.CREDITINFORMATION_CODIGORETORN ,
CONTROLE.CREDITINFORMATION_DATAHORACONS ,
CONTROLE.CREDITINFORMATION_DATAHORAFIM ,
CONTROLE.CREDITINFORMATION_DATAHORAINIC ,
CONTROLE.CREDITINFORMATION_DATARESPOSTA ,
CONTROLE.CREDITINFORMATION_MENSAGEM ,
CONTROLE.CREDITINFORMATION_TEMPOTOTAL ,
CONTROLE.INTERNALCHECK_TEMPOTO001 ,
CONTROLE.INTERNALCHECK_CHAMAR ,
CONTROLE.INTERNALCHECK_CHAMOU ,
CONTROLE.INTERNALCHECK_CODIGORETORNO ,
CONTROLE.INTERNALCHECK_DATAHORACONSULTA ,
CONTROLE.INTERNALCHECK_DATAHORAFIM ,
CONTROLE.INTERNALCHECK_DATAHORAINICIO ,
CONTROLE.INTERNALCHECK_DATARESPOSTA ,
CONTROLE.INTERNALCHECK_MENSAGEM ,
CONTROLE.INTERNALCHECK_TEMPOTO002 ,
CONTROLE.RETORNOMESANC_CHAMAR ,
CONTROLE.RETORNOMESANC_CHAMOU ,
CONTROLE.RETORNOMESANC_CODIGORETORNO ,
CONTROLE.RETORNOMESANC_DATAHORACONSULTA ,
CONTROLE.RETORNOMESANC_DATAHORAFIM ,
CONTROLE.RETORNOMESANC_DATAHORAINICIO ,
CONTROLE.RETORNOMESANC_DATARESPOSTA ,
CONTROLE.RETORNOMESANC_MENSAGEM ,
CONTROLE.RETORNOMESANC_TEMPOTOTAL ,
CONTROLE.DIASLOOKUP_BUREAU_NETCRACKER ,
CONTROLE.DIASLOOKUP_BUREAU_SALESFORCE ,
CONTROLE.DIASLOOKUP_DECISAO_NETCRACKER ,
CONTROLE.DIASLOOKUP_DECISAO_SALESFORCE ,
CONTROLE.FLAGLOOKUP_NETCRACKER ,
CONTROLE.FLAGLOOKUP_SALESFORCE ,
CONTROLE.DATAEXPIRACAOSLA ,
CONTROLE.FLAGFERIADO ,
CONTROLE.SLACONSUMIDO ,
CONTROLE.SLATOTAL ,
CONTROLE.BUSCAC1_HORAFIM ,
CONTROLE.BUSCAC1_HORAINICIO ,
CONTROLE.BUSCAC1_TEMPOTOTAL ,
CONTROLE.CODRETORNOANALISECREDITO ,
CONTROLE.DATAPOLITICAANALISECREDITO ,
CONTROLE.USUARIOBLOCK from CONTROLE INNER JOIN DADOSPROPOSTADS ON  CONTROLE.IDS_CONTROLE = DADOSPROPOSTADS.IDS_CONTROLE  and DADOSPROPOSTADS.IDS_DADOSPROPOSTADS = IDS_DADOSPROPOSTADS `;


/*
`SELECT 'CONTROLE' TABELA, 'INSERT' OPERACAO, SYSDATE DATA_STREAM, CONTROLE.* 
from CONTROLE , DADOSPROPOSTADS 
WHERE  CONTROLE.IDS_CONTROLE = DADOSPROPOSTADS.IDS_CONTROLE and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.IDS_DADOSPROPOSTADS = context.id;

    query += `\nwhere IDS_DADOSPROPOSTADS = :IDS_DADOSPROPOSTADS`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
