const database = require ('../../services/database');

const baseQuery =

`SELECT 'GETCREDITINFORMATION' TABELA, 'INSERT' OPERACAO, 
GETCREDITINFORMATION.IDS_GETCREDITINFORMATION ,
GETCREDITINFORMATION.ARRIDX_DADOSPROPOSTADS ,
GETCREDITINFORMATION.SYS_CREATEDATE ,
GETCREDITINFORMATION.SYSTEMNAME ,
GETCREDITINFORMATION.IDS_DADOSPROPOSTADS from GETCREDITINFORMATION `;

/*
`SELECT 'GETCREDITINFORMATION' TABELA, 'INSERT' OPERACAO, SYSDATE DATA_STREAM, GETCREDITINFORMATION.* 
from GETCREDITINFORMATION , DADOSPROPOSTADS 
WHERE GETCREDITINFORMATION.IDS_DADOSPROPOSTADS = DADOSPROPOSTADS.IDS_DADOSPROPOSTADS and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.IDS_DADOSPROPOSTADS = context.id;

    query += `\nwhere IDS_DADOSPROPOSTADS = :IDS_DADOSPROPOSTADS`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
