const database = require ('../../services/database');

const baseQuery =

`SELECT 'WHITELIST_PF_FIXO' TABELA, 'INSERT' OPERACAO, 
WHITELIST_PF_FIXO.IDS_WHITELIST_PF_FIXO ,
WHITELIST_PF_FIXO.COD_ARQ_PROCESSAR ,
WHITELIST_PF_FIXO.CODIGOERRO ,
WHITELIST_PF_FIXO.CPF ,
WHITELIST_PF_FIXO.DATA_WL ,
WHITELIST_PF_FIXO.DESCRICAOERRO ,
WHITELIST_PF_FIXO.MOTIVO ,
WHITELIST_PF_FIXO.PLANO ,
WHITELIST_PF_FIXO.SYS_CREATEDATE ,
WHITELIST_PF_FIXO.NOMECLIENTE from WHITELIST_PF_FIXO  INNER JOIN DADOSPROPOSTADS ON  WHITELIST_PF_FIXO.IDS_WHITELIST_PF_FIXO = DADOSPROPOSTADS.IDS_WHITELIST_PF_FIXO  and DADOSPROPOSTADS.IDS_DADOSPROPOSTADS = IDS_DADOSPROPOSTADS `;

/*
`SELECT 'WHITELIST_PF_FIXO' TABELA, 'INSERT' OPERACAO, SYSDATE DATA_STREAM, WHITELIST_PF_FIXO.* 
from WHITELIST_PF_FIXO , DADOSPROPOSTADS 
WHERE  WHITELIST_PF_FIXO.IDS_WHITELIST_PF_FIXO = DADOSPROPOSTADS.IDS_WHITELIST_PF_FIXO and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.IDS_DADOSPROPOSTADS = context.id;

    query += `\nwhere IDS_DADOSPROPOSTADS = :IDS_DADOSPROPOSTADS`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;

