const database = require ('../../services/database');

const baseQuery =

`SELECT 'ATLYS_RESP_LDS' TABELA, SYSDATE OPERACAO, 
TELEFONICA.ATLYS_RESP_LDS.IDS_ATLYS_RESP_LDS ,
TELEFONICA.ATLYS_RESP_LDS.CODIGO_RETORNO ,
TELEFONICA.ATLYS_RESP_LDS.DESC_RESTRICAO ,
TELEFONICA.ATLYS_RESP_LDS.FLAG_RESTRICAO ,
TELEFONICA.ATLYS_RESP_LDS.MENSAGEM ,
TELEFONICA.ATLYS_RESP_LDS.SCORE ,
TELEFONICA.ATLYS_RESP_LDS.SYS_CREATEDATE from ATLYS_RESP_LDS INNER JOIN DADOSPROPOSTADS ON  ATLYS_RESP_LDS.IDS_ATLYS_RESP_LDS = DADOSPROPOSTADS.IDS_ATLYS_RESP_LDS  and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA`;

/*
`SELECT 'ATLYS_RESP_LDS' NOME_TABELA, 
SYSDATE OPERACAO,
  
ATLYS_RESP_LDS.* 
from ATLYS_RESP_LDS inner join DADOSPROPOSTADS 
on  ATLYS_RESP_LDS.IDS_ATLYS_RESP_LDS = DADOSPROPOSTADS.IDS_ATLYS_RESP_LDS and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA`;

/*
`SELECT 'ATLYS_RESP_LDS' TABELA, SYSDATE OPERACAO, SYSDATE DATA_STREAM, ATLYS_RESP_LDS.* 
from ATLYS_RESP_LDS , DADOSPROPOSTADS 
WHERE  ATLYS_RESP_LDS.IDS_ATLYS_RESP_LDS = DADOSPROPOSTADS.IDS_ATLYS_RESP_LDS and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.NUMPROPOSTA = context.id;

    query += `\nwhere NUMPROPOSTA = :NUMPROPOSTA`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;

