const database = require ('../../services/database');

const baseQuery =

`SELECT 'AUDITORIAPOLITICA' TABELA, SYSDATE OPERACAO, 
TELEFONICA.AUDITORIAPOLITICA.IDS_AUDITORIAPOLITICA ,
TELEFONICA.AUDITORIAPOLITICA.ALIASDA ,
TELEFONICA.AUDITORIAPOLITICA.ANALISEINTERNA_DECISIONPROCESS ,
TELEFONICA.AUDITORIAPOLITICA.ANALISEINTERNA_DEPLOYDATETIME ,
TELEFONICA.AUDITORIAPOLITICA.ANALISEINTERNA_DEPLOYUSERID ,
TELEFONICA.AUDITORIAPOLITICA.ANALISEINTERNA_EDITIONNUMBER ,
TELEFONICA.AUDITORIAPOLITICA.ANALISEINTERNA_SIGNATURE ,
TELEFONICA.AUDITORIAPOLITICA.ANALISEINTERNA_SOFTWAREVERSION ,
TELEFONICA.AUDITORIAPOLITICA.ANALISEINTERNA_STATUS ,
TELEFONICA.AUDITORIAPOLITICA.CHAMADABUREAU_DECISIONPROCESSF ,
TELEFONICA.AUDITORIAPOLITICA.CHAMADABUREAU_DEPLOYDATETIME ,
TELEFONICA.AUDITORIAPOLITICA.CHAMADABUREAU_DEPLOYUSERID ,
TELEFONICA.AUDITORIAPOLITICA.CHAMADABUREAU_EDITIONNUMBER ,
TELEFONICA.AUDITORIAPOLITICA.CHAMADABUREAU_SIGNATURE ,
TELEFONICA.AUDITORIAPOLITICA.CHAMADABUREAU_SOFTWAREVERSION ,
TELEFONICA.AUDITORIAPOLITICA.CHAMADABUREAU_STATUS ,
TELEFONICA.AUDITORIAPOLITICA.DECISAOFINAL_DECISIONPROCESSFL ,
TELEFONICA.AUDITORIAPOLITICA.DECISAOFINAL_DEPLOYDATETIME ,
TELEFONICA.AUDITORIAPOLITICA.DECISAOFINAL_DEPLOYUSERID ,
TELEFONICA.AUDITORIAPOLITICA.DECISAOFINAL_EDITIONNUMBER ,
TELEFONICA.AUDITORIAPOLITICA.DECISAOFINAL_SIGNATURE ,
TELEFONICA.AUDITORIAPOLITICA.DECISAOFINAL_SOFTWAREVERSION ,
TELEFONICA.AUDITORIAPOLITICA.DECISAOFINAL_STATUS ,
TELEFONICA.AUDITORIAPOLITICA.PARAMETROS_DECISIONPROCESSFLOW ,
TELEFONICA.AUDITORIAPOLITICA.PARAMETROS_DEPLOYDATETIME ,
TELEFONICA.AUDITORIAPOLITICA.PARAMETROS_DEPLOYUSERID ,
TELEFONICA.AUDITORIAPOLITICA.PARAMETROS_EDITIONNUMBER ,
TELEFONICA.AUDITORIAPOLITICA.PARAMETROS_SIGNATURE ,
TELEFONICA.AUDITORIAPOLITICA.PARAMETROS_SOFTWAREVERSION ,
TELEFONICA.AUDITORIAPOLITICA.PARAMETROS_STATUS ,
TELEFONICA.AUDITORIAPOLITICA.SUBLDS ,
TELEFONICA.AUDITORIAPOLITICA.SYS_CREATEDATE from AUDITORIAPOLITICA INNER JOIN DADOSPROPOSTADS ON  AUDITORIAPOLITICA.IDS_AUDITORIAPOLITICA = DADOSPROPOSTADS.IDS_AUDITORIAPOLITICA  and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA `;

/*
`SELECT 'AUDITORIAPOLITICA' TABELA, SYSDATE OPERACAO, SYSDATE DATA_STREAM, AUDITORIAPOLITICA.* 
from AUDITORIAPOLITICA , DADOSPROPOSTADS 
WHERE  AUDITORIAPOLITICA.IDS_AUDITORIAPOLITICA = DADOSPROPOSTADS.IDS_AUDITORIAPOLITICA and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.NUMPROPOSTA = context.id;

    query += `\nwhere NUMPROPOSTA = :NUMPROPOSTA`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
