const database = require ('../../services/database');

const baseQuery =

`SELECT 'CALLCENTER_REQ_LDS' TABELA, 
SYSDATE OPERACAO, 
CALLCENTER_REQ_LDS.IDS_CALLCENTER_REQ_LDS ,
CALLCENTER_REQ_LDS.CEP ,
CALLCENTER_REQ_LDS.DOCUMENTO ,
CALLCENTER_REQ_LDS.DTNASC ,
CALLCENTER_REQ_LDS.SYS_CREATEDATE ,
CALLCENTER_REQ_LDS.USUARIO from CALLCENTER_REQ_LDS INNER JOIN DADOSPROPOSTADS ON  CALLCENTER_REQ_LDS.IDS_CALLCENTER_REQ_LDS = DADOSPROPOSTADS.IDS_CALLCENTER_REQ_LDS  and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA `;

/*
`SELECT 'CALLCENTER_REQ_LDS' TABELA, SYSDATE OPERACAO, SYSDATE DATA_STREAM, CALLCENTER_REQ_LDS.* 
from CALLCENTER_REQ_LDS , DADOSPROPOSTADS 
WHERE  CALLCENTER_REQ_LDS.IDS_CALLCENTER_REQ_LDS = DADOSPROPOSTADS.IDS_CALLCENTER_REQ_LDS and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.NUMPROPOSTA = context.id;

    query += `\nwhere NUMPROPOSTA = :NUMPROPOSTA`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;

