const database = require ('../../services/database');

const baseQuery =

`SELECT 'CALLCENTER_RESP_LDS' TABELA, SYSDATE OPERACAO, 
CALLCENTER_RESP_LDS.IDS_CALLCENTER_RESP_LDS ,
CALLCENTER_RESP_LDS.CODIGO_COR ,
CALLCENTER_RESP_LDS.CODIGO_PLANO ,
CALLCENTER_RESP_LDS.CODIGO_RETORNO ,
CALLCENTER_RESP_LDS.DESC_RESTRICAO ,
CALLCENTER_RESP_LDS.FAIXA_CEP ,
CALLCENTER_RESP_LDS.FLAG_RESTRICAO ,
CALLCENTER_RESP_LDS.MENSAGEM ,
CALLCENTER_RESP_LDS.RECOMENDACAO_POLITICA ,
CALLCENTER_RESP_LDS.SCORE ,
CALLCENTER_RESP_LDS.SYS_CREATEDATE from CALLCENTER_RESP_LDS INNER JOIN DADOSPROPOSTADS ON  CALLCENTER_RESP_LDS.IDS_CALLCENTER_RESP_LDS = DADOSPROPOSTADS.IDS_CALLCENTER_RESP_LDS  and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA`;


/*
`SELECT 'CALLCENTER_RESP_LDS' TABELA, SYSDATE OPERACAO, SYSDATE DATA_STREAM, CALLCENTER_RESP_LDS.* 
from CALLCENTER_RESP_LDS , DADOSPROPOSTADS 
WHERE  CALLCENTER_RESP_LDS.IDS_CALLCENTER_RESP_LDS = DADOSPROPOSTADS.IDS_CALLCENTER_RESP_LDS and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.NUMPROPOSTA = context.id;

    query += `\nwhere NUMPROPOSTA = :NUMPROPOSTA`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
