const database = require ('../../services/database');

const baseQuery =

`SELECT 'CONSULTACREDITO_REQ' TABELA, SYSDATE OPERACAO, 
CONSULTACREDITO_REQ.IDS_CONSULTACREDITO_REQ ,
CONSULTACREDITO_REQ.CEP ,
CONSULTACREDITO_REQ.DATANASCIMENTO ,
CONSULTACREDITO_REQ.DOCUMENTO ,
CONSULTACREDITO_REQ.NOMECLIENTE ,
CONSULTACREDITO_REQ.NOMEMAE ,
CONSULTACREDITO_REQ.SENHAGESTO ,
CONSULTACREDITO_REQ.SENHASERASA ,
CONSULTACREDITO_REQ.SYS_CREATEDATE ,
CONSULTACREDITO_REQ.USUARIOGESTOR ,
CONSULTACREDITO_REQ.USUARIOSERASA from CONSULTACREDITO_REQ INNER JOIN DADOSPROPOSTADS ON  CONSULTACREDITO_REQ.IDS_CONSULTACREDITO_REQ = DADOSPROPOSTADS.IDS_CONSULTACREDITO_REQ  and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA `;

/*
`SELECT 'CONSULTACREDITO_REQ' TABELA, SYSDATE OPERACAO, SYSDATE DATA_STREAM, CONSULTACREDITO_REQ.* 
from CONSULTACREDITO_REQ , DADOSPROPOSTADS 
WHERE  CONSULTACREDITO_REQ.IDS_CONSULTACREDITO_REQ = DADOSPROPOSTADS.IDS_CONSULTACREDITO_REQ and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.NUMPROPOSTA = context.id;

    query += `\nwhere NUMPROPOSTA = :NUMPROPOSTA`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
