const database = require ('../../services/database');

const baseQuery =

`SELECT 'CUSTOMERCREDIT_DS' TABELA, 'INSERT' OPERACAO, 
CUSTOMERCREDIT_DS.IDS_CUSTOMERCREDIT_DS ,
CUSTOMERCREDIT_DS.ACCOUNTID ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE0TO30_AMOUNTINVOI ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE121TO150_AMOUNTIN ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE151TO180_AMOUNTIN ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE181TO210_AMOUNTIN ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE1TO2YEARS_AMOUNTI ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE211TO240_AMOUNTIN ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE241TO270_AMOUNTIN ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE271TO300_AMOUNTIN ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE2TO3YEARS_AMOUNTI ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE301TO330_AMOUNTIN ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE31TO60_AMOUNTINVO ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE331TO1YEAR_AMOUNT ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE3TO4YEARS_AMOUNTI ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE4TO5YEARS_AMOUNTI ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE5ORMOREYEARS_AMOU ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE61TO90_AMOUNTINVO ,
CUSTOMERCREDIT_DS.AMOUNTINVOICE91TO120_AMOUNTINV ,
CUSTOMERCREDIT_DS.AMOUNTINVOUCEOVERALL_AMOUNTINV ,
CUSTOMERCREDIT_DS.ARRIDX_GETCREDITINFORMATION ,
CUSTOMERCREDIT_DS.LASTCONTESTATION_AMOUNTINVO003 ,
CUSTOMERCREDIT_DS.LASTCONTESTATION_AMOUNTINVO001 ,
CUSTOMERCREDIT_DS.LASTCONTESTATION_AMOUNTINVO002 ,
CUSTOMERCREDIT_DS.LASTCONTESTATION_BILLINGINQ002 ,
CUSTOMERCREDIT_DS.LASTCONTESTATION_BILLINGINQ001 ,
CUSTOMERCREDIT_DS.LASTCONTESTATION_REFERENCEMONT ,
CUSTOMERCREDIT_DS.PRODUCTLINE_TYPE ,
CUSTOMERCREDIT_DS.SUBSCRIPTION_AMOUNTSUBSCRIP001 ,
CUSTOMERCREDIT_DS.SUBSCRIPTION_AMOUNTSUBSCRIP002 ,
CUSTOMERCREDIT_DS.SUBSCRIPTION_AMOUNTSUBSCRIP003 ,
CUSTOMERCREDIT_DS.SUBSCRIPTION_AMOUNTSUBSCRIP004 ,
CUSTOMERCREDIT_DS.SUBSCRIPTION_AMOUNTSUBSCRIP005 ,
CUSTOMERCREDIT_DS.SUBSCRIPTION_SUBSCRIPTIONDA004 ,
CUSTOMERCREDIT_DS.SUBSCRIPTION_SUBSCRIPTIONDA003 ,
CUSTOMERCREDIT_DS.SUBSCRIPTION_SUBSCRIPTIONDA002 ,
CUSTOMERCREDIT_DS.SUBSCRIPTION_SUBSCRIPTIONDA001 ,
CUSTOMERCREDIT_DS.SYS_CREATEDATE ,
CUSTOMERCREDIT_DS.TRANSACTIONID ,
CUSTOMERCREDIT_DS.IDS_GETCREDITINFORMATION ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN001 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN005 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN006 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN007 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN013 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN008 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN009 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN010 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN014 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN011 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN002 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN012 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN015 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN016 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN017 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN003 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTIN004 ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_AMOUNTINVOU ,
CUSTOMERCREDIT_DS.BALANCEINFORMATION_HASPAYMENTI ,
CUSTOMERCREDIT_DS.LEGALID_NATIONALID ,
CUSTOMERCREDIT_DS.LEGALID_NATIONALIDTYPE from CUSTOMERCREDIT_DS 
INNER JOIN GETCREDITINFORMATION on CUSTOMERCREDIT_DS.IDS_GETCREDITINFORMATION = GETCREDITINFORMATION.IDS_GETCREDITINFORMATION  
INNER JOIN DADOSPROPOSTADS ON GETCREDITINFORMATION.IDS_DADOSPROPOSTADS = DADOSPROPOSTADS.IDS_DADOSPROPOSTADS 
and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA `;


/*
`SELECT 'CUSTOMERCREDIT_DS' TABELA, SYSDATE OPERACAO, SYSDATE DATA_STREAM, CUSTOMERCREDIT_DS.* 
from CUSTOMERCREDIT_DS, GETCREDITINFORMATION, DADOSPROPOSTADS 
WHERE GETCREDITINFORMATION.IDS_DADOSPROPOSTADS = DADOSPROPOSTADS.IDS_DADOSPROPOSTADS and CUSTOMERCREDIT_DS.IDS_GETCREDITINFORMATION = GETCREDITINFORMATION.IDS_GETCREDITINFORMATION and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/


async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.NUMPROPOSTA = context.id;

    query += `\nwhere NUMPROPOSTA = :NUMPROPOSTA`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
