const database = require ('../../services/database');

const baseQuery =

`SELECT 'DOCUMENTSINFORMATION_DS' TABELA, 'INSERT' OPERACAO, 
DOCUMENTSINFORMATION_DS.IDS_DOCUMENTSINFORMATION_DS ,
DOCUMENTSINFORMATION_DS.AMOUNTINVOICEDOCUMENT_AMOUNTIN ,
DOCUMENTSINFORMATION_DS.AMOUNTINVOICEREMAINING_AMOUNTI ,
DOCUMENTSINFORMATION_DS.AMOUNTPAYMENT_AMOUNTINVOICE ,
DOCUMENTSINFORMATION_DS.AMOUNTRESIDUALINVOICEADJUST_AM ,
DOCUMENTSINFORMATION_DS.AMOUNTRESIDUALINVOICEDISPUTE_A ,
DOCUMENTSINFORMATION_DS.ARRIDX_CUSTOMERCREDIT_DS ,
DOCUMENTSINFORMATION_DS.BILLDATE_ENDDATETIME ,
DOCUMENTSINFORMATION_DS.BILLDATE_STARTDATETIME ,
DOCUMENTSINFORMATION_DS.LASTBILLDATE_ENDDATETIME ,
DOCUMENTSINFORMATION_DS.LASTBILLDATE_STARTDATETIME ,
DOCUMENTSINFORMATION_DS.PAYMENTDATE ,
DOCUMENTSINFORMATION_DS.PAYMENTDUEDATE_ENDDATETIME ,
DOCUMENTSINFORMATION_DS.PAYMENTDUEDATE_STARTDATETIME ,
DOCUMENTSINFORMATION_DS.REFERENCEMONTHYEAR ,
DOCUMENTSINFORMATION_DS.STATUS ,
DOCUMENTSINFORMATION_DS.SYS_CREATEDATE ,
DOCUMENTSINFORMATION_DS.IDS_CUSTOMERCREDIT_DS ,
DOCUMENTSINFORMATION_DS.BILLNO from DOCUMENTSINFORMATION_DS INNER JOIN CUSTOMERCREDIT_DS ON DOCUMENTSINFORMATION_DS.IDS_CUSTOMERCREDIT_DS = CUSTOMERCREDIT_DS.IDS_CUSTOMERCREDIT_DS 
INNER JOIN GETCREDITINFORMATION ON CUSTOMERCREDIT_DS.IDS_GETCREDITINFORMATION = GETCREDITINFORMATION.IDS_GETCREDITINFORMATION 
INNER JOIN DADOSPROPOSTADS ON GETCREDITINFORMATION.IDS_DADOSPROPOSTADS = DADOSPROPOSTADS.IDS_DADOSPROPOSTADS and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA `;


/*
`SELECT 'DOCUMENTSINFORMATION_DS' TABELA, SYSDATE OPERACAO, SYSDATE DATA_STREAM, DOCUMENTSINFORMATION_DS.* 
from DOCUMENTSINFORMATION_DS, CUSTOMERCREDIT_DS, DADOSPROPOSTADS 
WHERE  CUSTOMERCREDIT_DS.IDS_CUSTOMERCREDIT_DS = DOCUMENTSINFORMATION_DS.IDS_CUSTOMERCREDIT_DS and DOCUMENTSINFORMATION_DS.IDS_DOCUMENTSINFORMATION_DS = CUSTOMERCREDIT_DS.IDS_GETCREDITINFORMATION and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.NUMPROPOSTA = context.id;

    query += `\nwhere NUMPROPOSTA = :NUMPROPOSTA`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
