const database = require ('../../services/database');

const baseQuery =

`SELECT 'EXCECAOCREDITO_REQDS' TABELA, 'INSERT' OPERACAO, 
EXCECAOCREDITO_REQDS.IDS_EXCECAOCREDITO_REQDS ,
EXCECAOCREDITO_REQDS.DESCRICAO ,
EXCECAOCREDITO_REQDS.DOCUMENTO ,
EXCECAOCREDITO_REQDS.NUMEROCASO ,
EXCECAOCREDITO_REQDS.SYS_CREATEDATE ,
EXCECAOCREDITO_REQDS.TIPODOCUMENTO from EXCECAOCREDITO_REQDS INNER JOIN DADOSPROPOSTADS ON  EXCECAOCREDITO_REQDS.IDS_EXCECAOCREDITO_REQDS = DADOSPROPOSTADS.IDS_EXCECAOCREDITO_REQDS  and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA `;


/*
`SELECT 'EXCECAOCREDITO_RESPDS' TABELA, SYSDATE OPERACAO, SYSDATE DATA_STREAM, EXCECAOCREDITO_RESPDS.* 
from EXCECAOCREDITO_RESPDS , DADOSPROPOSTADS 
WHERE  EXCECAOCREDITO_RESPDS.IDS_EXCECAOCREDITO_RESPDS = DADOSPROPOSTADS.IDS_EXCECAOCREDITO_RESPDS and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/


async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.NUMPROPOSTA = context.id;

    query += `\nwhere NUMPROPOSTA = :NUMPROPOSTA`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;

