const database = require ('../../services/database');

const baseQuery =

`SELECT 'GETCREDITINFORMATION' TABELA, 'INSERT' OPERACAO, 
GETCREDITINFORMATION.IDS_GETCREDITINFORMATION ,
GETCREDITINFORMATION.ARRIDX_DADOSPROPOSTADS ,
GETCREDITINFORMATION.SYS_CREATEDATE ,
GETCREDITINFORMATION.SYSTEMNAME ,
GETCREDITINFORMATION.IDS_DADOSPROPOSTADS from GETCREDITINFORMATION INNER JOIN DADOSPROPOSTADS ON GETCREDITINFORMATION.IDS_DADOSPROPOSTADS = DADOSPROPOSTADS.IDS_DADOSPROPOSTADS  and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA `;

/*
`SELECT 'GETCREDITINFORMATION' TABELA, SYSDATE OPERACAO, SYSDATE DATA_STREAM, GETCREDITINFORMATION.* 
from GETCREDITINFORMATION , DADOSPROPOSTADS 
WHERE GETCREDITINFORMATION.IDS_DADOSPROPOSTADS = DADOSPROPOSTADS.IDS_DADOSPROPOSTADS and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.NUMPROPOSTA = context.id;

    query += `\nwhere NUMPROPOSTA = :NUMPROPOSTA`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
