const database = require ('../../services/database');

const baseQuery =


`SELECT 'GETDEBTSINF_RESPDS' TABELA, 'INSERT' OPERACAO, 
GETDEBTSINF_RESPDS.IDS_GETDEBTSINF_RESPDS ,
GETDEBTSINF_RESPDS.ACCOUNTID ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE0TO30 ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE121TO150 ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE151TO180 ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE181TO210 ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE1TO2YEARS ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE211TO240 ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE241TO270 ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE271TO300 ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE2TO3YEARS ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE301TO330 ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE31TO60 ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE331TO1YEAR ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE3TO4YEARS ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE4TO5YEARS ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE5ORMOREYEARS ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE61TO90 ,
GETDEBTSINF_RESPDS.AMOUNTINVOICE91TO120 ,
GETDEBTSINF_RESPDS.ARRIDX_DADOSPROPOSTADS ,
GETDEBTSINF_RESPDS.COMPANYNAME ,
GETDEBTSINF_RESPDS.DOCUMENTNUMBER ,
GETDEBTSINF_RESPDS.EXECUTIONCODE ,
GETDEBTSINF_RESPDS.EXECUTIONDESCRIPTION ,
GETDEBTSINF_RESPDS.HASPAYMENTINSTALLMENTS ,
GETDEBTSINF_RESPDS.MESSAGE ,
GETDEBTSINF_RESPDS.NATIONALIDENTILYCARDNR ,
GETDEBTSINF_RESPDS.PRODUCTLINE ,
GETDEBTSINF_RESPDS.SYS_CREATEDATE ,
GETDEBTSINF_RESPDS.SYSTEMNAME ,
GETDEBTSINF_RESPDS.VALORESEMABERTO ,
GETDEBTSINF_RESPDS.VALORESEMABERTOMAIOR30D ,
GETDEBTSINF_RESPDS.IDS_DADOSPROPOSTADS from GETDEBTSINF_RESPDS inner join DADOSPROPOSTADS on GETDEBTSINF_RESPDS.IDS_DADOSPROPOSTADS = DADOSPROPOSTADS.IDS_DADOSPROPOSTADS and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA `;





async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.NUMPROPOSTA = context.id;

    query += `\nwhere NUMPROPOSTA = :NUMPROPOSTA`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
