const database = require ('../../services/database');

const baseQuery =

`SELECT 'HP_FS_DS' TABELA, SYSDATE OPERACAO, 
HP_FS_DS.IDS_HP_FS_DS ,
HP_FS_DS.REQUEST_BAIRRO ,
HP_FS_DS.REQUEST_CEP ,
HP_FS_DS.REQUEST_CIDADE ,
HP_FS_DS.REQUEST_COMPLEMENTO ,
HP_FS_DS.REQUEST_CPFCNPJ ,
HP_FS_DS.REQUEST_DATANASCIMENTO ,
HP_FS_DS.REQUEST_ENDERECO ,
HP_FS_DS.REQUEST_IDENDERECO ,
HP_FS_DS.REQUEST_NOMEMAE ,
HP_FS_DS.REQUEST_NUMERO ,
HP_FS_DS.REQUEST_PDV ,
HP_FS_DS.REQUEST_PROPOSTA ,
HP_FS_DS.REQUEST_RG ,
HP_FS_DS.REQUEST_SISTEMAORIGEM ,
HP_FS_DS.REQUEST_TELCONTATO ,
HP_FS_DS.REQUEST_UF ,
HP_FS_DS.RESPONSE_CODRETORNO ,
HP_FS_DS.RESPONSE_CPFCNPJ ,
HP_FS_DS.RESPONSE_DSCRETORNO ,
HP_FS_DS.RESPONSE_PONTUACAO ,
HP_FS_DS.RESPONSE_RECOMENDACAO ,
HP_FS_DS.SYS_CREATEDATE from HP_FS_DS inner join DADOSPROPOSTADS on HP_FS_DS.IDS_HP_FS_DS = DADOSPROPOSTADS.IDS_HP_FS_DS  and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA `;






async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.NUMPROPOSTA = context.id;

    query += `\nwhere NUMPROPOSTA = :NUMPROPOSTA`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
