const database = require ('../../services/database');

const baseQuery =

`SELECT 'REQUESTBASECEPVIVODS' TABELA, SYSDATE OPERACAO, 
REQUESTBASECEPVIVODS.IDS_REQUESTBASECEPVIVODS ,
REQUESTBASECEPVIVODS.CEPENTRADA ,
REQUESTBASECEPVIVODS.SYS_CREATEDATE ,
REQUESTBASECEPVIVODS.CEPENTRADA_CEP_358 ,
REQUESTBASECEPVIVODS.CEPENTRADA_FLAG_CEP3 ,
REQUESTBASECEPVIVODS.CEPENTRADA_FLAG_CEP5 ,
REQUESTBASECEPVIVODS.CEPENTRADA_FLAG_CEP8 ,
REQUESTBASECEPVIVODS.CEP3 ,
REQUESTBASECEPVIVODS.CEP5 ,
REQUESTBASECEPVIVODS.CEP8 from REQUESTBASECEPVIVODS  
INNER JOIN DADOSPROPOSTADS ON  REQUESTBASECEPVIVODS.IDS_REQUESTBASECEPVIVODS = DADOSPROPOSTADS.IDS_REQUESTBASECEPVIVODS  and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA `;

/*
`SELECT 'REQUESTBASECEPVIVODS' TABELA, SYSDATE OPERACAO, SYSDATE DATA_STREAM, REQUESTBASECEPVIVODS.* 
from REQUESTBASECEPVIVODS , DADOSPROPOSTADS 
WHERE  REQUESTBASECEPVIVODS.IDS_REQUESTBASECEPVIVODS = DADOSPROPOSTADS.IDS_REQUESTBASECEPVIVODS and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.NUMPROPOSTA = context.id;

    query += `\nwhere NUMPROPOSTA = :NUMPROPOSTA`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
