const database = require ('../../services/database');

const baseQuery =

`SELECT 'SERA11_PF' TABELA, SYSDATE OPERACAO, 
SERA11_PF.IDS_SERA11_PF ,
SERA11_PF.CHEQUESEMFUNDO_AGENCIAULTOCORR ,
SERA11_PF.CHEQUESEMFUNDO_BANCOULTOCORREN ,
SERA11_PF.CHEQUESEMFUNDO_DATAULTOCORRENC ,
SERA11_PF.CHEQUESEMFUNDO_MENSAGEM ,
SERA11_PF.CHEQUESEMFUNDO_QUANTIDADETOTAL ,
SERA11_PF.CONSULTACHEQUE_QUANTIDADEATUAL ,
SERA11_PF.CONSULTACHEQUE_QUANTIDADEMES1 ,
SERA11_PF.CONSULTACHEQUE_QUANTIDADEMES2 ,
SERA11_PF.CONSULTACHEQUE_QUANTIDADEMES3 ,
SERA11_PF.CONSULTACPF_QUANTIDADEMES1 ,
SERA11_PF.CONSULTACPF_QUANTIDADEMES2 ,
SERA11_PF.CONSULTACPF_QUANTIDADEMES3 ,
SERA11_PF.CONSULTACPF_QUANTIDADEMESATUAL ,
SERA11_PF.CONSULTACPF_QUANTIDADETOTAL ,
SERA11_PF.DATACONSULTA ,
SERA11_PF.DOCUMENTOS_DATAOCORRENCIA ,
SERA11_PF.FALENCIAEMPRESARIAIS_DATAOCORR ,
SERA11_PF.FALENCIAEMPRESARIAIS_MENSAGEM ,
SERA11_PF.FALENCIAEMPRESARIAIS_QUANTIDAD ,
SERA11_PF.GRAFIA_DADOSCADASTRAIS_DEPENDE ,
SERA11_PF.GRAFIA_DADOSCADASTRAIS_ESTADOC ,
SERA11_PF.GRAFIA_DADOSCADASTRAIS_INSTRUC ,
SERA11_PF.GRAFIA_DADOSCADASTRAIS_NACIONA ,
SERA11_PF.GRAFIA_DADOSCADASTRAIS_NOMEMAE ,
SERA11_PF.GRAFIA_DADOSCADASTRAIS_SEXO ,
SERA11_PF.GRAFIA_IDENTIFICACAO_CPF ,
SERA11_PF.GRAFIA_IDENTIFICACAO_DATAAT001 ,
SERA11_PF.GRAFIA_IDENTIFICACAO_DATAAT002 ,
SERA11_PF.GRAFIA_IDENTIFICACAO_DATANASCI ,
SERA11_PF.GRAFIA_IDENTIFICACAO_GRAFIA ,
SERA11_PF.GRAFIA_IDENTIFICACAO_IDADE ,
SERA11_PF.GRAFIA_IDENTIFICACAO_REGIAOCPF ,
SERA11_PF.GRAFIA_IDENTIFICACAO_SITUACAO ,
SERA11_PF.GRAFIA_LOCALIZACAO_BAIRRO ,
SERA11_PF.GRAFIA_LOCALIZACAO_CEP ,
SERA11_PF.GRAFIA_LOCALIZACAO_CIDADE ,
SERA11_PF.GRAFIA_LOCALIZACAO_DDD1 ,
SERA11_PF.GRAFIA_LOCALIZACAO_DDD2 ,
SERA11_PF.GRAFIA_LOCALIZACAO_ENDERECO ,
SERA11_PF.GRAFIA_LOCALIZACAO_FONE1 ,
SERA11_PF.GRAFIA_LOCALIZACAO_FONE2 ,
SERA11_PF.GRAFIA_LOCALIZACAO_UF ,
SERA11_PF.GRAFIASEMELHANTE_DADOSCADAS006 ,
SERA11_PF.GRAFIASEMELHANTE_DADOSCADAS005 ,
SERA11_PF.GRAFIASEMELHANTE_DADOSCADAS002 ,
SERA11_PF.GRAFIASEMELHANTE_DADOSCADAS004 ,
SERA11_PF.GRAFIASEMELHANTE_DADOSCADAS001 ,
SERA11_PF.GRAFIASEMELHANTE_DADOSCADAS003 ,
SERA11_PF.GRAFIASEMELHANTE_IDENTIFICA002 ,
SERA11_PF.GRAFIASEMELHANTE_IDENTIFICA005 ,
SERA11_PF.GRAFIASEMELHANTE_IDENTIFICA007 ,
SERA11_PF.GRAFIASEMELHANTE_IDENTIFICA003 ,
SERA11_PF.GRAFIASEMELHANTE_IDENTIFICA001 ,
SERA11_PF.GRAFIASEMELHANTE_IDENTIFICA004 ,
SERA11_PF.GRAFIASEMELHANTE_IDENTIFICA008 ,
SERA11_PF.GRAFIASEMELHANTE_IDENTIFICA006 ,
SERA11_PF.GRAFIASEMELHANTE_LOCALIZACAO_B ,
SERA11_PF.GRAFIASEMELHANTE_LOCALIZACA002 ,
SERA11_PF.GRAFIASEMELHANTE_LOCALIZACA001 ,
SERA11_PF.GRAFIASEMELHANTE_LOCALIZACA003 ,
SERA11_PF.GRAFIASEMELHANTE_LOCALIZACA004 ,
SERA11_PF.GRAFIASEMELHANTE_LOCALIZACAO_E ,
SERA11_PF.GRAFIASEMELHANTE_LOCALIZACA005 ,
SERA11_PF.GRAFIASEMELHANTE_LOCALIZACA006 ,
SERA11_PF.GRAFIASEMELHANTE_LOCALIZACAO_U ,
SERA11_PF.HORACONSULTA ,
SERA11_PF.MENSAGEM_CODIGO ,
SERA11_PF.MENSAGEM_MENSAGEM ,
SERA11_PF.OUTRAGRAFIA_DADOSCADASTRAIS_DE ,
SERA11_PF.OUTRAGRAFIA_DADOSCADASTRAIS_ES ,
SERA11_PF.OUTRAGRAFIA_DADOSCADASTRAIS_IN ,
SERA11_PF.OUTRAGRAFIA_DADOSCADASTRAIS_NA ,
SERA11_PF.OUTRAGRAFIA_DADOSCADASTRAIS_NO ,
SERA11_PF.OUTRAGRAFIA_DADOSCADASTRAIS_SE ,
SERA11_PF.OUTRAGRAFIA_IDENTIFICACAO_CPF ,
SERA11_PF.OUTRAGRAFIA_IDENTIFICACAO_D002 ,
SERA11_PF.OUTRAGRAFIA_IDENTIFICACAO_D003 ,
SERA11_PF.OUTRAGRAFIA_IDENTIFICACAO_D001 ,
SERA11_PF.OUTRAGRAFIA_IDENTIFICACAO_GRAF ,
SERA11_PF.OUTRAGRAFIA_IDENTIFICACAO_IDAD ,
SERA11_PF.OUTRAGRAFIA_IDENTIFICACAO_REGI ,
SERA11_PF.OUTRAGRAFIA_IDENTIFICACAO_SITU ,
SERA11_PF.OUTRAGRAFIA_LOCALIZACAO_BAIRRO ,
SERA11_PF.OUTRAGRAFIA_LOCALIZACAO_CEP ,
SERA11_PF.OUTRAGRAFIA_LOCALIZACAO_CIDADE ,
SERA11_PF.OUTRAGRAFIA_LOCALIZACAO_DDD1 ,
SERA11_PF.OUTRAGRAFIA_LOCALIZACAO_DDD2 ,
SERA11_PF.OUTRAGRAFIA_LOCALIZACAO_ENDERE ,
SERA11_PF.OUTRAGRAFIA_LOCALIZACAO_FONE1 ,
SERA11_PF.OUTRAGRAFIA_LOCALIZACAO_FONE2 ,
SERA11_PF.OUTRAGRAFIA_LOCALIZACAO_UF ,
SERA11_PF.PARTICIPACAOEMPRESA_MENSAGEM ,
SERA11_PF.PARTICIPACAOEMPRESA_QUANTIDADE ,
SERA11_PF.PEFIN_DATAMAISANTIGA ,
SERA11_PF.PEFIN_DATAMAISRECENTE ,
SERA11_PF.PEFIN_DESCRICAO ,
SERA11_PF.PEFIN_EMPRESA ,
SERA11_PF.PEFIN_FILIAL ,
SERA11_PF.PEFIN_MENSAGEM ,
SERA11_PF.PEFIN_TIPO ,
SERA11_PF.PEFIN_TIPOMOEDA ,
SERA11_PF.PEFIN_TOTAL ,
SERA11_PF.PEFIN_TOTALPEFIN ,
SERA11_PF.PEFIN_TOTALREFIN ,
SERA11_PF.PEFIN_VALORULTIMAOCORRENCIA ,
SERA11_PF.PROTESTOS_DATAMAIOR ,
SERA11_PF.PROTESTOS_DATAPRIMEIRO ,
SERA11_PF.PROTESTOS_MENSAGEM ,
SERA11_PF.PROTESTOS_QUANTIDADETOTAL ,
SERA11_PF.PROTESTOS_TIPOMOEDA ,
SERA11_PF.PROTESTOS_VALORMAIOR ,
SERA11_PF.PROTESTOS_VALORPRIMEIRO ,
SERA11_PF.PROTESTOS_VALORTOTAL ,
SERA11_PF.SYS_CREATEDATE from SERA11_PF  INNER JOIN DADOSPROPOSTADS ON  SERA11_PF.IDS_SERA11_PF = DADOSPROPOSTADS.IDS_SERA11_PF  and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA `;


/*
`SELECT 'SERA11_PF' TABELA, SYSDATE OPERACAO, SYSDATE DATA_STREAM, SERA11_PF.* 
from SERA11_PF , DADOSPROPOSTADS 
WHERE  SERA11_PF.IDS_SERA11_PF = DADOSPROPOSTADS.IDS_SERA11_PF and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575'`;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.NUMPROPOSTA = context.id;

    query += `\nwhere NUMPROPOSTA = :NUMPROPOSTA`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;

