const database = require ('../../services/database');

const baseQuery =

`SELECT 'WHITELIST_PJ_FIXO' TABELA, SYSDATE OPERACAO, 
WHITELIST_PJ_FIXO.IDS_WHITELIST_PJ_FIXO ,
WHITELIST_PJ_FIXO.CNPJ ,
WHITELIST_PJ_FIXO.COD_ARQ_PROCESSAR ,
WHITELIST_PJ_FIXO.CODIGOERRO ,
WHITELIST_PJ_FIXO.DATA_CADASTRO ,
WHITELIST_PJ_FIXO.DESCRICAOERRO ,
WHITELIST_PJ_FIXO.MOTIVO ,
WHITELIST_PJ_FIXO.PLANO ,
WHITELIST_PJ_FIXO.SYS_CREATEDATE ,
WHITELIST_PJ_FIXO.NOMECLIENTE from WHITELIST_PJ_FIXO  INNER JOIN DADOSPROPOSTADS ON  WHITELIST_PJ_FIXO.IDS_WHITELIST_PJ_FIXO = DADOSPROPOSTADS.IDS_WHITELIST_PJ_FIXO  and DADOSPROPOSTADS.NUMPROPOSTA = NUMPROPOSTA `;

/*
`SELECT 'WHITELIST_PJ_MOVEL' TABELA, SYSDATE OPERACAO, SYSDATE DATA_STREAM, WHITELIST_PJ_MOVEL.* 
from WHITELIST_PJ_MOVEL , DADOSPROPOSTADS 
WHERE  WHITELIST_PJ_MOVEL.IDS_WHITELIST_PJ_MOVEL = DADOSPROPOSTADS.IDS_WHITELIST_PJ_MOVEL and DADOSPROPOSTADS.NUMPROPOSTA = '000000000521575' `;
**/

async function find(context) {
  let query = baseQuery;
  const binds = {};

  if (context.id) {
    binds.NUMPROPOSTA = context.id;

    query += `\nwhere NUMPROPOSTA = :NUMPROPOSTA`;
  }

  const result = await database.simpleExecute(query, binds);

  return result.rows;
}

module.exports.find = find;
